version: '3.8'

services:
  terraform:
    build: .
    container_name: terraform
    environment:
      - AWS_ACCESS_KEY_ID=ACESS_KEY
      - AWS_SECRET_ACCESS_KEY=SUA_SENHA_ACESSO
      - AWS_REGION=us-east-1
    volumes:
      - ./infra:/workspace
    working_dir: /workspace